### ISSUE TITLE
Alphabetical sorting of my downloads 

### ISSUE THREAD

**Issue by ERJAJOHANNA** [avorg/audioverse-mobile#1]
Hi,
I have used both the audioverse App and downloaded sermons to iTunes on my computer. I found it easy to listen again to my downloads in iTunes because it they are listed alphabetically. When I see the list of what I have downloaded and listened to in iTunes it provides a good source of sermons for me to share with others to listen to (especially new people I met later on). Otherwise I forget what sermons might be good for them.  The sermons that I have downloaded and listened to on the App are just a list and it  takes too long time to find the sermons I would like to share with others or listen to again. Is it possible to have something similar to the capability of computer iTunes downloads?
Regards,
Johanna

**Comment by alangumer** [comment]
Hi @ERJAJOHANNA thank you for the suggestion, we'll have that in mind for next releases.

**Comment by narthur** [comment]
Would be good if we had multiple sort options in downloads list:

- Alphabetical
- Speaker
- Date
- Conference
- Series

Etc.

**Comment by mattleff** [comment]
Moving to https://trello.com/c/GOOc0Rxz/58-app-ui-redesign.
