### ISSUE TITLE
Sonos Compatible Option

### ISSUE THREAD

**Issue by dlamberton** [avorg/audioverse-mobile#11]
Was wondering if there is a way to get audioverse to play on Sonos Home Speakers. I can get podcasts to work via podcast app but full Audioverse content is not available through the podcast app.

**Comment by alangumer** [comment]
Download the official AudioVerse app from the app store. It should work as long as you have your Sonos Home Speakers paired to your phone. Blessings.

**Comment by dlamberton** [comment]
Thank you for your reply, 

Well I’m not sure that solution will work...I don’t pair my Sonos speakers to my phone directly I play music and audio through their sonos app and their app didn’t recognize the audioverse app. It’s not just a Bluetooth pairing solution I wish it was.

Danny Lamberton
509 952 4063
dannylamberton@gmail.com

**Comment by alangumer** [comment]
I see... those speakers work through Wi-Fi.

Are you using an Android or iPhone? if you are using an iPhone, use the podcast app, search for the AudioVerse, download the presentation and it should appear under Browse in your Sonos app.
Another alternative for both Android and iOS is to use the Google Play Music app to stream music/podcasts, in the Google Play Music, go to Podcats, search for Audioverse, select Audiovese latest recordings, select one presentation and then click the cast button on the top right corner.

Hope it helps.

Ref:
https://support.sonos.com/s/article/321?language=en_US
https://play.google.com/about/music/sonos/

**Comment by dlamberton** [comment]
Yes I’ve tried audioverse in podcast that works but what audioverse has on podcast is quite limited and doesn't provide the ability to find certain archived presentations that I want to select...

Danny Lamberton
509 952 4063
dannylamberton@gmail.com

**Comment by alangumer** [comment]
True, the podcasts feed is not as complete as the data from the official AudioVerse app, I would suggest to download the AudioVerse app and download the presentations there and then look them up in your Sonos app.

**Comment by dlamberton** [comment]
Ok Thank you 

Danny Lamberton
509 952 4063
dannylamberton@gmail.com
