### ISSUE TITLE
Play Store review: Difficulty looking up GYC conferences

### ISSUE THREAD

**Issue by narthur** [avorg/audioverse-mobile#13]
> Buenas quisiera reportar que es muy difícil encontrar los congresos de GYC por año o lugar. Al intentar revisar por series no aparece nada. Desde ya muchas gracias.

Google Translate:

> Good I would like to report that it is very difficult to find the GYC congresses by year or place. When trying to review by series nothing appears. Thank you very much.

**Comment by narthur** [comment]
How can we allow people to drill down from conference to a series at that conference within the app?

Someone brought this issue to my attention at GYC, too.

**Comment by mattleff** [comment]
Moving to https://trello.com/c/GOOc0Rxz/58-app-ui-redesign.
