### ISSUE TITLE
Messages Restarting when App Loses Focus

### ISSUE THREAD

**Issue by narthur** [avorg/audioverse-mobile#16]
Email from Al:

> In the past two days I’ve had several users inform me of a bug in our mobile app. The summary of the issue is that when a user listens to a sermon in the app, hit pause, then switch to another app or turn off the screen, when they return to the app, the entire message restarts and plays from the beginning—losing their place.
>
> I don’t recall this being an issue with the app before, and I don’t think it’s the intended behavior. These users are all on iOS and I read somewhere that iOS 13 had some wonky RAM management issues that causes a lot of apps to need frequent refreshing. (I noticed this with my Safari browser tabs after I upgraded, they would not be retained but they were refreshing every time I switched tabs.) So perhaps this is an iOS issue, but nevertheless it’s something we need to look into.

**Comment by narthur** [comment]
@alangumer This needs to be priority.

**Comment by ahuong** [comment]
The app used to have a feature that popped up asking users whether they want to begin listening the message where they left off, and if they accept, it should remember the timestamp of where to start the recording.

**Comment by narthur** [comment]
What if, in the future, it didn't ask, but simply started where the person left off? The person can always manually restart the presentation. I believe this is how most apps do it.

**Comment by ahuong** [comment]
Yes, Henry clarified that that's actually how it is supposed to behave now. In fact, I checked that the app functions properly by remembering where I left off AS LONG AS THE FILE WAS DOWNLOADED. The loss of position apparently occurs only for streaming media.
