### ISSUE TITLE
Find more intuitive icons for bottom navigation

### ISSUE THREAD

**Issue by narthur** [avorg/audioverse-mobile#26]
Problematic icons:
- Discover
- Bible
- Books

Could we also show the labels even when the section is not selected?

**Comment by alangumer** [comment]
Please pick the ones that you think are best https://feathericons.com/

**Comment by alangumer** [comment]
@narthur Bottom Navigation guidelines and API
https://material.io/components/bottom-navigation/#usage
https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html

**Comment by ahuong** [comment]
From that site, how about the following:

1. Audiobook = "book" or "book-open" from feathericons.com
2. Bible = Use the current book w/ bookmark icon for Audiobooks
3. Discover = I don't see any that are better than the one we're using right now.

If we also keep the labels persistent, it will go a long way to making the icons understandable.

**Comment by alangumer** [comment]
@ahuong and @narthur  I just realized that the icons that we are using are https://material.io/resources/icons/?style=baseline, please pick from there.

**Comment by ahuong** [comment]
A lot more options on this one. Here would be my choices:

1. Audiobook = "menu_book" or "library_books"
2. Bible = "Book"
3. Discover = "Dashboard"
