### ISSUE TITLE
Play Store review: Can't delete recordings from My Lists

### ISSUE THREAD

**Issue by narthur** [avorg/audioverse-mobile#27]
> Need to fix My Lists. Won't allow you to delete anything. The recordings just come back and repopulate the list.

**Comment by alangumer** [comment]
This is an API error, delete favorite and delete playlist item are not working, check the endpoints:
1. favorite/delete
2. playlist/recording/0 -- delete playlist item

**Comment by narthur** [comment]
Ok. I've added an issue to the API repository:

https://github.com/avorg/audioverse-api/issues/20
