### ISSUE TITLE
Should we make Favorites, Playlists, and History top-level items?

### ISSUE THREAD

**Issue by narthur** [avorg/audioverse-mobile#35]
This was prompted by some feedback that a user gave regarding having difficulty getting back to an audiobook that they had really liked. They did figure out how to find it again, but after some frustration.

I wondered if the app had history and couldn't find it until Al told me it was under "My Lists." I assumed from the item title that this was only referring to my personal playlists, and wouldn't have known to look for Favorites and History here.

Should we move all the items under "My Lists" to top-level items to make them more discoverable?

**Comment by mattleff** [comment]
Moving to https://trello.com/c/GOOc0Rxz/58-app-ui-redesign.
