### ISSUE TITLE
Make mini player dismissable

### ISSUE THREAD

**Issue by narthur** [avorg/audioverse-mobile#49]
I've talked with two people so far who were confused by the fact that there was no way to close the miniplayer.

**Comment by narthur** [comment]
Stitcher's mini-player isn't dismissable. Is there something else we could do to make things more intuitive without actually making the mini-player dismissable?

**Comment by mattleff** [comment]
Moving to https://trello.com/c/GOOc0Rxz/58-app-ui-redesign.
