### ISSUE TITLE
Pause/Stop Feature 

### ISSUE THREAD

**Issue by hiker1** [AVORG/audioverse-mobile#7]
I use the AudioVerse app most of the time in my car. It would be wonderful if the app would stop playing when a call is answered and then resume when the call is disconnected like my audiobook apps do. 

The other thing that would be very handy is for it to stop playing completely when it detects that the wired headphones have been disconnected or when bluetooth-audio has been been disconnected. 

Both of these are features in my audiobook apps that I just love as a commuter. That way when I get back in my car after work it just picks right back up where I left off.

**Comment by alangumer** [comment]
Added on the last version.
