### ISSUE TITLE
release to Android

### ISSUE THREAD

**Issue by tr33house** [AVORG/audioverse-mobile#9]
It looks like it's been a while since Android was released. Just checked out master and a lot of the issues are already solved. It'll be nice to release this externally

**Comment by alangumer** [comment]
We'll release to the app stores as soon as we finish with the [todos](https://github.com/AVORG/audioverse-mobile#todos) which pairs functionality with the existing version on the store :)

**Comment by tr33house** [comment]
How about releasing after every TODO instead of batching all of them at once
